#!/bin/sh
# GENERATED by tools/gen.py from schemes/ — do not edit.
# Wana Dark
[ "$TERM" = "linux" ] || exit 0
printf '%b' '\e]P032302f\e]P1fe8b89\e]P27abb87\e]P3fabd2f\e]P480b7f0\e]P5d3869b\e]P68ec07c\e]P7ebdbb2\e]P8a89984\e]P9ffa09d\e]PA8dd69c\e]PBffd636\e]PC93d1ff\e]PDf39bb3\e]PEa3dc8f\e]PFfbf1c7'
