#!/bin/sh
# GENERATED by tools/gen.py from schemes/ — do not edit.
# Wana Light
[ "$TERM" = "linux" ] || exit 0
printf '%b' '\e]P0f2f0e5\e]P1bc4039\e]P22d6e3f\e]P3956c00\e]P41c6aae\e]P5a02f6f\e]P6218078\e]P7100f0f\e]P86f6e69\e]P9a61619\e]PA015826\e]PB805300\e]PC00529b\e]PD8a0059\e]PE006a62\e]PF282726'
